/** Verified BSC addresses only. Unverified issuers stay unsupported. */
export const TOKENS = {
  NVDA: [
    {
      issuer: "bstocks",
      name: "bStocks",
      symbol: "NVDAB",
      address: "0x02fca66c1d1afb4e2a7884261eb00f63598a7436",
      ratio: 1,
      hours: "regular",
      verified: true,
      source: "Binance Web3 eligible bStock list",
    },
    {
      issuer: "ondo",
      name: "Ondo",
      symbol: "NVDAon",
      address: "0xa9ee28c80f960b889dfbd1902055218cba016f75",
      ratio: 1,
      hours: "regular",
      verified: true,
      source: "Binance Alpha listing / DexScreener",
    },
    {
      issuer: "xstocks",
      name: "xStocks",
      symbol: "NVDAx",
      address: null,
      ratio: 1,
      hours: "always",
      verified: false,
      source: "No verified BSC contract found. Backed lists Ethereum/Solana only.",
    },
  ],
  AAPL: [
    {
      issuer: "bstocks",
      name: "bStocks",
      symbol: "AAPLB",
      address: "0x431a3bee82e2ca41e49895cbece5bb0f76a89b7a",
      ratio: 1,
      hours: "regular",
      verified: true,
      source: "Binance Web3 eligible bStock list",
    },
    {
      issuer: "ondo",
      name: "Ondo",
      symbol: "AAPLon",
      address: null,
      ratio: 1,
      hours: "regular",
      verified: false,
      source: "BSC address not verified in this build",
    },
    {
      issuer: "xstocks",
      name: "xStocks",
      symbol: "AAPLx",
      address: null,
      ratio: 1,
      hours: "always",
      verified: false,
      source: "BSC address not verified in this build",
    },
  ],
  AMZN: [
    {
      issuer: "bstocks",
      name: "bStocks",
      symbol: "AMZNB",
      address: "0x1a4b499833a79a09ad7cf1d42d7dacf71e92eb00",
      ratio: 1,
      hours: "regular",
      verified: true,
      source: "Binance Web3 eligible bStock list",
    },
    {
      issuer: "ondo",
      name: "Ondo",
      symbol: "AMZNon",
      address: null,
      ratio: 1,
      hours: "regular",
      verified: false,
      source: "BSC address not verified in this build",
    },
    {
      issuer: "xstocks",
      name: "xStocks",
      symbol: "AMZNx",
      address: null,
      ratio: 1,
      hours: "always",
      verified: false,
      source: "BSC address not verified in this build",
    },
  ],
};

export const TICKERS = Object.keys(TOKENS);
